// Built-in appearance data. This module intentionally contains plain data so
// custom theme import/export can stay stable and easy to review.

export const THEMES = {
  default: {
    label: "Default",
    bg: "aurora",
    crt: false,
    grain: "0.05",
    vars: { "--accent": "#7aa2f7", "--accent-2": "#bb9af7", "--radius": "14px", "--pane-alpha": "0.55" },
    xterm: {
      background: "rgba(0,0,0,0)",
      foreground: "#c0caf5",
      cursor: "#7aa2f7",
      cursorAccent: "#0b0d1a",
      selectionBackground: "rgba(122,162,247,0.35)",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },
  retro: {
    label: "Modern Retro",
    bg: "retro",
    crt: true,
    grain: "0.10",
    vars: { "--accent": "#ff4f9a", "--accent-2": "#36f9f6", "--radius": "8px", "--pane-alpha": "0.42" },
    xterm: {
      background: "rgba(0,0,0,0)",
      foreground: "#f6e9ff",
      cursor: "#ff4f9a",
      cursorAccent: "#1b0b2e",
      selectionBackground: "rgba(255,79,154,0.35)",
      black: "#1b0b2e",
      red: "#fe4450",
      green: "#72f1b8",
      yellow: "#fede5d",
      blue: "#36f9f6",
      magenta: "#ff7edb",
      cyan: "#36f9f6",
      white: "#f6e9ff",
      brightBlack: "#8a6fb0",
      brightRed: "#fe4450",
      brightGreen: "#72f1b8",
      brightYellow: "#fede5d",
      brightBlue: "#36f9f6",
      brightMagenta: "#ff7edb",
      brightCyan: "#36f9f6",
      brightWhite: "#ffffff",
    },
  },
  forest: {
    label: "Nature Forest",
    bg: "forest",
    crt: false,
    grain: "0.04",
    vars: { "--accent": "#8cb369", "--accent-2": "#4f9d8f", "--radius": "20px", "--pane-alpha": "0.5" },
    xterm: {
      background: "rgba(0,0,0,0)",
      foreground: "#d8e0d0",
      cursor: "#8cb369",
      cursorAccent: "#0a160f",
      selectionBackground: "rgba(140,179,105,0.35)",
      black: "#1b2a1f",
      red: "#e76f51",
      green: "#95d5b2",
      yellow: "#e9c46a",
      blue: "#74c69d",
      magenta: "#a3b18a",
      cyan: "#74c69d",
      white: "#d8e0d0",
      brightBlack: "#5f6f5a",
      brightRed: "#e76f51",
      brightGreen: "#95d5b2",
      brightYellow: "#e9c46a",
      brightBlue: "#74c69d",
      brightMagenta: "#a3b18a",
      brightCyan: "#74c69d",
      brightWhite: "#eef2ea",
    },
  },
  mono: {
    label: "Monochrome",
    bg: "mono",
    crt: false,
    grain: "0.06",
    vars: { "--accent": "#bdbdbd", "--accent-2": "#7a7a7a", "--radius": "6px", "--pane-alpha": "0.5" },
    xterm: {
      background: "rgba(0,0,0,0)",
      foreground: "#e6e6e6",
      cursor: "#e6e6e6",
      cursorAccent: "#1a1a1a",
      selectionBackground: "rgba(200,200,200,0.30)",
      black: "#2a2a2a",
      red: "#9a9a9a",
      green: "#bcbcbc",
      yellow: "#d2d2d2",
      blue: "#8a8a8a",
      magenta: "#a8a8a8",
      cyan: "#c4c4c4",
      white: "#e6e6e6",
      brightBlack: "#5a5a5a",
      brightRed: "#b4b4b4",
      brightGreen: "#d4d4d4",
      brightYellow: "#e2e2e2",
      brightBlue: "#a0a0a0",
      brightMagenta: "#c2c2c2",
      brightCyan: "#dcdcdc",
      brightWhite: "#ffffff",
    },
  },
  ocean: {
    label: "Ocean",
    bg: "ocean",
    crt: false,
    grain: "0.04",
    vars: { "--accent": "#38bdf8", "--accent-2": "#2dd4bf", "--radius": "16px", "--pane-alpha": "0.5" },
    xterm: {
      background: "rgba(0,0,0,0)",
      foreground: "#cdeeff",
      cursor: "#38bdf8",
      cursorAccent: "#04181f",
      selectionBackground: "rgba(56,189,248,0.30)",
      black: "#0a2230",
      red: "#ff7a7a",
      green: "#34d399",
      yellow: "#fcd34d",
      blue: "#38bdf8",
      magenta: "#818cf8",
      cyan: "#2dd4bf",
      white: "#cdeeff",
      brightBlack: "#3a5a6a",
      brightRed: "#ff9a9a",
      brightGreen: "#6ee7b7",
      brightYellow: "#fde68a",
      brightBlue: "#7dd3fc",
      brightMagenta: "#a5b4fc",
      brightCyan: "#5eead4",
      brightWhite: "#eafaff",
    },
  },
  ferrari: {
    label: "Ferrari",
    bg: "ferrari",
    crt: false,
    grain: "0.05",
    vars: { "--accent": "#ff2800", "--accent-2": "#ffd200", "--radius": "8px", "--pane-alpha": "0.55" },
    xterm: {
      background: "rgba(0,0,0,0)",
      foreground: "#fff2f0",
      cursor: "#ff2800",
      cursorAccent: "#1a0303",
      selectionBackground: "rgba(255,40,0,0.30)",
      black: "#1a0303",
      red: "#ff2800",
      green: "#7bd13b",
      yellow: "#ffd200",
      blue: "#5a9bd4",
      magenta: "#ff5e7a",
      cyan: "#4dd0e1",
      white: "#fff2f0",
      brightBlack: "#5a2020",
      brightRed: "#ff5a3c",
      brightGreen: "#9ee05a",
      brightYellow: "#ffe24d",
      brightBlue: "#7ab8e8",
      brightMagenta: "#ff85a0",
      brightCyan: "#72e0ef",
      brightWhite: "#ffffff",
    },
  },
  claude: {
    label: "Claude",
    bg: "claude",
    crt: false,
    grain: "0.05",
    vars: { "--accent": "#da7756", "--accent-2": "#e3a47f", "--radius": "14px", "--pane-alpha": "0.5" },
    xterm: {
      background: "rgba(0,0,0,0)",
      foreground: "#f0eee6",
      cursor: "#da7756",
      cursorAccent: "#1f1410",
      selectionBackground: "rgba(218,119,86,0.30)",
      black: "#2a1c14",
      red: "#da7756",
      green: "#a3a380",
      yellow: "#d4a27f",
      blue: "#8a9a9a",
      magenta: "#c08552",
      cyan: "#a8b5a0",
      white: "#f0eee6",
      brightBlack: "#5a463a",
      brightRed: "#e8956f",
      brightGreen: "#b9b896",
      brightYellow: "#e3b894",
      brightBlue: "#a4b2b2",
      brightMagenta: "#d39e6a",
      brightCyan: "#bcc6b6",
      brightWhite: "#faf9f5",
    },
  },
  mario: {
    label: "Super Mario",
    bg: "mario",
    crt: false,
    grain: "0.05",
    vars: { "--accent": "#e52521", "--accent-2": "#ffffff", "--radius": "4px", "--pane-alpha": "0.5" },
    xterm: {
      background: "rgba(0,0,0,0)",
      foreground: "#ffffff",
      cursor: "#e52521",
      cursorAccent: "#1a1a2a",
      selectionBackground: "rgba(229,37,33,0.30)",
      black: "#3a1d0c",
      red: "#e52521",
      green: "#43b047",
      yellow: "#fbd000",
      blue: "#049cd8",
      magenta: "#e54590",
      cyan: "#5fcde4",
      white: "#ffffff",
      brightBlack: "#7a4a2a",
      brightRed: "#ff5a4a",
      brightGreen: "#6ed06a",
      brightYellow: "#ffe24d",
      brightBlue: "#43b8f0",
      brightMagenta: "#ff6aa8",
      brightCyan: "#8ae0f0",
      brightWhite: "#ffffff",
    },
  },
};

export const SCENES = ["aurora", "retro", "forest", "mono", "ocean", "ferrari", "claude", "mario"];

export const ACCENTS = [
  { a: "#7aa2f7", b: "#bb9af7" },
  { a: "#bb9af7", b: "#7dcfff" },
  { a: "#9ece6a", b: "#7dcfff" },
  { a: "#f7768e", b: "#ff9e64" },
  { a: "#ff9e64", b: "#e0af68" },
  { a: "#7dcfff", b: "#9ece6a" },
];
